### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [grothjef/Dota2DB#1]
There are a couple things I'd like updated here, detailed below:
### Validation tweaks

You're using `validates_presence_of` for `:name`, though it looks like you're really trying to validate the format. In this case, those extra parameters you're passing in to `validates_precence_of` simply aren't doing anything, apart from `message`.

Since turn rates will always be greater than 0 and less than or equal to 1, I think a validation checking for this makes more sense than checking the number against regex as a string.
### Indentation

I see some hard-tabs in this project. The standard indentation for Ruby (`.rb`) files is two-space soft-tabs. And in Rails projects, it's actually best practice to have _every_ file use two-space soft-tabs.

Can you [reconfigure your text editor](https://github.com/chrisvfritz/tc359_cheatsheets/blob/master/ruby/indentation.md) to use two-space soft-tabs instead? And then afterwards, update all your files to use that indentation. You may also find [this video](https://www.youtube.com/watch?v=_JFIeY46sIU) and [this video](https://www.youtube.com/watch?v=GMf8dlrEbB4) helpful for Sublime Text.

---

Let me know when you've updated these and I'll take another look. If you get stuck, also please don't hesitate to let me know and I'll be happy to point you in the right direction.

**Comment by chrisvfritz** [comment]
Any progress here?

**Comment by grothjef** [comment]
Hopefully I can get both of my issues taken care of tomorrow

**Comment by chrisvfritz** [comment]
Excellent. Just comment here to let me know when it's taken care of.

**Comment by grothjef** [comment]
So i think i fixed the name validation
But,
I didnt know how to do the turnrate validating that it's less than one and greater than zero

**Comment by chrisvfritz** [comment]
Check out [these docs on Rails numericality](http://guides.rubyonrails.org/active_record_validations.html#numericality) validation.

**Comment by grothjef** [comment]
Do believe I have fixed it

**Comment by chrisvfritz** [comment]
The validations look good now, but the indentation problems still exist, which means this didn't quite make it to an approvable state before the deadline unfortunately.
